### ISSUE TITLE
Support fine-tuning on uploaded data

### ISSUE THREAD

**Issue by jupyterjazz** [jina-ai/finetuner#414] opened 2022-05-31 06:44 UTC
Currently we don't support fine-tuning on already uploaded data which is important if you have large data and don't want to upload it every time you run a fine-tuning job.

**Comment by jupyterjazz** [comment] 2022-05-31 08:10
Turns out, in a way, this is already supported.

When I pass a valid data name, everything works well.

When an invalid name is passed, following error is triggered:
`HTTPError: 404 Client Error: Not Found for url: https://apihubble.staging.jina.ai/v2/rpc/artifact.getDownloadUrl?name=sabas-clip-data-10`

which is not perfect, but enough for now. 

I'll revisit this issue later.

**Comment by gmastrapas** [comment] 2022-06-10 13:15
Duplicate of https://github.com/jina-ai/finetuner.fit/issues/254

**Closed** 2022-06-10 13:15 UTC
